---
title: "Final Project Check-In"
output: github_document
---


## Github Repositories

[Shiny application](https://github.com/ahvickers/accident_shiny_project)
Tag: v0.1.1, commit 835cbf7

[R package](https://github.com/ahvickers/accidenttracker)
Tag: v0.1.1, commit 7a69c69

## Accident Tracker Project Description

The application accident_tracker and its associated functions will serve as a tool to filter and present information related to accidents in an easy accessible format, so it will be a tool and also include some analysis.

There will be a total of two git repositories for the project, one for the shiny application and one for the package containing the necessary functions for the app to run. These repositories are owned by a single group member, with the remaining three members all having forked versions of them. Any changes done by a single group member are initially done on the forked version before a pull request is sent to the main repositories and the versions merged if no issues arise and the changes are agreed upon. This is similar to the Integration-Manager Workflow in the Git Pro textbook.

Our project will include the following elements:
- A package with documented functions
    -Functioning unit tests for the package
- An inclusive vignette
- A shiny application capable of reading accident data from a chosen data set along with numerous variables
- A detailed ui allowing for the toggling of filters using reactive code.
  - Display precipitation, weather, severity on a color scale
  - Variable sizes of data clusters depending on zoom level (city, county, state).
- Implementation of different tabs to increase functionality
  - i.e. Graphical elements to highlight relationships between certain variables.


